Nov 07 20:53:42 wafflefm bash[2617977]: Traceback (most recent call last):
Nov 07 20:53:42 wafflefm bash[2617977]:   File "/home/cody/waffle/.venv/lib/python3.10/site-packages/discord/app_commands/commands.py", line 857, in _do_call
Nov 07 20:53:42 wafflefm bash[2617977]:     return await self._callback(self.binding, interaction, **params)  # type: ignore
Nov 07 20:53:42 wafflefm bash[2617977]:   File "/home/cody/waffle/cogs/debrid.py", line 65, in mag
Nov 07 20:53:42 wafflefm bash[2617977]:     mag = await self.alldebrid.upload_magnets(magnet)
Nov 07 20:53:42 wafflefm bash[2617977]: TypeError: object dict can't be used in 'await' expression
Nov 07 20:53:42 wafflefm bash[2617977]: The above exception was the direct cause of the following exception:
Nov 07 20:53:42 wafflefm bash[2617977]: Traceback (most recent call last):
Nov 07 20:53:42 wafflefm bash[2617977]:   File "/home/cody/waffle/.venv/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1310, in _call
Nov 07 20:53:42 wafflefm bash[2617977]:     await command._invoke_with_namespace(interaction, namespace)
Nov 07 20:53:42 wafflefm bash[2617977]:   File "/home/cody/waffle/.venv/lib/python3.10/site-packages/discord/app_commands/commands.py", line 883, in _invoke_with_namespace
Nov 07 20:53:42 wafflefm bash[2617977]:     return await self._do_call(interaction, transformed_values)
Nov 07 20:53:42 wafflefm bash[2617977]:   File "/home/cody/waffle/.venv/lib/python3.10/site-packages/discord/app_commands/commands.py", line 872, in _do_call
Nov 07 20:53:42 wafflefm bash[2617977]:     raise CommandInvokeError(self, e) from e
Nov 07 20:53:42 wafflefm bash[2617977]: discord.app_commands.errors.CommandInvokeError: Command 'magnet' raised an exception: TypeError: object dict can't be used in 'await' expression

^ fix magnet command

redo debrid download flow

maybe fix m3u